# Generated by Django 5.2.3 on 2025-06-27 15:02

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_create_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Product name", max_length=200)),
                ("description", models.TextField(help_text="Detailed product description")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Product price (must be positive)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("sqm", "Square Meters"),
                            ("piece", "Piece"),
                            ("slab", "Slab"),
                            ("linear_m", "Linear Meters"),
                        ],
                        help_text="Unit of measurement for pricing and quantity",
                        max_length=20,
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0, help_text="Current stock quantity")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this product is active and visible"),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Stock Keeping Unit (optional, must be unique if provided)",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Product category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
                "ordering": ["name"],
            },
        ),
    ]
