# Generated by Django 5.2.3 on 2025-06-27 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_create_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(help_text="Product image file", upload_to="products/")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, help_text="Alternative text for accessibility", max_length=200, null=True
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Whether this is the primary/main image for the product"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, help_text="Order for displaying images (0 = first)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this image belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "db_table": "product_images",
                "ordering": ["product", "display_order", "created_at"],
                "unique_together": {("product", "display_order")},
            },
        ),
    ]
