# Generated by Django 5.2.4 on 2025-10-27 12:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_create_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                help_text="Product image file (stored on Cloudinary)", max_length=255, verbose_name="image"
            ),
        ),
    ]
