# Generated by Django 5.2.4 on 2025-09-14 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_create_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Product price (must be positive)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
